name: Custom JSON Validation
description: Custom GitHub Action to validate a JSON file against a schema
inputs:
  json-file:
    description: 'Path to the JSON file'
    required: true
  schema-file:
    description: 'Path to the schema file'
    required: true
outputs:
  json:
    description: 'JSON content'
runs:
  using: 'node12'
  main: 'index.js'
