name: Planner

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0' # Run at 00:00 on every Sunday

jobs:
  planner-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Validate JSON
        id: validation
        run: |
          npm install ajv
          node .github/actions/planner-action/index.js

      - name: Extract JSON Content
        id: extract_content
        run: |
          json_content=$(cat ./recipe/cmake/recipe.json)
          echo "JSON Content: $json_content"

      - name: Test Outputs
        run: |
          echo "Substrate Tag: ${{ env.substrate_tag }}"
          echo "Substrate Name: ${{ env.substrate_name }}"
          echo "Substrate Registry: ${{ env.substrate_registry }}"
          echo "Substrate Auth: ${{ env.substrate_auth }}"
